In [3]:
!pip install numpy

                                              0.0/14.8 MB ? eta -:--:--
                                             0.0/14.8 MB 660.6 kB/s eta 0:00:23
                                             0.1/14.8 MB 656.4 kB/s eta 0:00:23
                                             0.1/14.8 MB 726.2 kB/s eta 0:00:21
                                             0.1/14.8 MB 708.1 kB/s eta 0:00:21
                                             0.2/14.8 MB 756.6 kB/s eta 0:00:20
                                             0.2/14.8 MB 731.4 kB/s eta 0:00:21
                                             0.2/14.8 MB 752.5 kB/s eta 0:00:20
                                             0.3/14.8 MB 739.6 kB/s eta 0:00:20
                                             0.3/14.8 MB 731.4 kB/s eta 0:00:20
                                             0.3/14.8 MB 723.4 kB/s eta 0:00:21
                                             0.4/14.8 MB 739.0 kB/s eta 0:00:20
     -                                       0.4

In [4]:
import numpy as np

##### Basics

In [5]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [6]:
b=np.array([[1.0,2.0],[3.0,4.0],[5.0,6.0]])
print(b)

[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [12]:
#getting dimension of the array
a.ndim

1

In [13]:
b.ndim

2

In [14]:
#getting the order of matrix
a.shape

(4,)

In [15]:
b.shape

(3, 2)

In [16]:
#getting the type of data in numpy array
a.dtype

dtype('int32')

In [17]:
b.dtype

dtype('float64')

In [18]:
#getting number of elements present in array
a.itemsize

4

In [19]:
b.itemsize

8

In [20]:
#getting the total bytes data occupied by the array
a.size*a.itemsize

16

In [24]:
b.size*b.itemsize

48

In [32]:
#indexing for 1-d matrix
print(a[2])
print(a[:])
print(a[0::2])
print(a[1::2])

3
[1 2 3 4]
[1 3]
[2 4]


In [35]:
#indexing for 2-d matrix
print(b[0,1])
print(b[0,:])#prints the 1st row
print(b[:,1])#prints the 2nd column
print(b[0:2:1,0])#[start_index:end_index:step_count]

2.0
[1. 2.]
[2. 4. 6.]
[1. 3.]
