In [1]:
!pip install numpy

In [4]:
import numpy as np

##### initializing different arrays

In [6]:
#creating identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
#creating a matrix of zeroes
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
#creating a matrix of ones
np.ones([4,2])

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [10]:
#creating an matrix of certain elements
np.full((3,3),8)

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [11]:
#creating a matrix of random numbers
np.random.rand(2,3,3)

array([[[0.38972471, 0.62412505, 0.42303229],
        [0.32261077, 0.37057623, 0.57448692],
        [0.60628144, 0.03678772, 0.1519745 ]],

       [[0.94472191, 0.018633  , 0.54328688],
        [0.59070808, 0.92376936, 0.92868142],
        [0.02752191, 0.71757778, 0.36774591]]])

In [12]:
#creating a matrix of random integers
np.random.randint(1,20,size=(3,2))

array([[ 1,  4],
       [ 2, 18],
       [14, 11]])

problem 1:

In [13]:
o=np.ones((5,5))
z=np.zeros((3,3))
z[1,1]=9
o[1:4,1:4]=z
print(o)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
