In [2]:
import numpy as np

##### Linear algebra

In [5]:
a=np.ones((2,3))
print('a=',a)
b=np.full((3,2),2)
print("b=",b)

a= [[1. 1. 1.]
 [1. 1. 1.]]
b= [[2 2]
 [2 2]
 [2 2]]


In [6]:
#matrix multiplication
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [7]:
#determinant
c=np.identity(5)
np.linalg.det(c)

1.0

In [8]:
#dot product of two matrices
np.dot(a,b)

array([[6., 6.],
       [6., 6.]])

In [9]:
#vector dot product
np.vdot(a,b)

12.0

In [11]:
#inverse of matrix
np.linalg.inv([[1,2],[3,4]])

array([[-2. ,  1. ],
       [ 1.5, -0.5]])