In [2]:
import numpy as np

##### Operations

In [3]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [4]:
#addition
print(a+2)

[3 4 5 6 7]


In [5]:
#subtraction
print(a-2)

[-1  0  1  2  3]


In [6]:
#multiplication
print(a*2)

[ 2  4  6  8 10]


In [7]:
#division
print(a/2)

[0.5 1.  1.5 2.  2.5]


In [8]:
#sine
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [9]:
#cosine
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [16]:
#concantenate
b=np.array([6,7,8,9,0])
np.concatenate((a,b),axis=0)

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [17]:
#sum
a.sum()

15

In [18]:
#max
a.max()

5

In [19]:
#min
a.min()

1

In [20]:
#sum or diff of two matrices
a+b

array([ 7,  9, 11, 13,  5])

In [21]:
#matrix mutiplication cannot be done rather the elements get directly multiplied
a*b

array([ 6, 14, 24, 36,  0])

In [22]:
np.flip(a)

array([5, 4, 3, 2, 1])