Compute the Kronecker product of two multidimension NumPy arrays

In [1]:
# Importing required modules
import numpy

# Creating arrays
array1 = numpy.array([[1, 2], [3, 4]])
print('Array1:\n', array1)

array2 = numpy.array([[5, 6], [7, 8]])
print('\nArray2:\n', array2)

# Computing the Kronecker Product
kroneckerProduct = numpy.kron(array1, array2)
print('\nArray1 ⊗ Array2:')
print(kroneckerProduct)

Array1:
 [[1 2]
 [3 4]]

Array2:
 [[5 6]
 [7 8]]

Array1 ⊗ Array2:
[[ 5  6 10 12]
 [ 7  8 14 16]
 [15 18 20 24]
 [21 24 28 32]]


NumPy – Fibonacci Series using Binet Formula

In [2]:
import numpy as np

# We are creating an array contains n = 10 elements
# for getting first 10 Fibonacci numbers
a = np.arange(1, 11)
lengthA = len(a)

# splitting of terms for easiness
sqrtFive = np.sqrt(5)
alpha = (1 + sqrtFive) / 2
beta = (1 - sqrtFive) / 2

# Implementation of formula
# np.rint is used for rounding off to integer
Fn = np.rint(((alpha ** a) - (beta ** a)) / (sqrtFive))
print("The first {} numbers of Fibonacci series are {} . ".format(lengthA, Fn))

The first 10 numbers of Fibonacci series are [ 1.  1.  2.  3.  5.  8. 13. 21. 34. 55.] . 


How to compute the eigenvalues and right eigenvectors of a given square array using NumPY?

In [4]:
# importing numpy library
import numpy as np

# create numpy 2d-array
m = np.array([[1, 2],
            [2, 3]])

print("Printing the Original square array:\n",
    m)

# finding eigenvalues and eigenvectors
w, v = np.linalg.eig(m)

# printing eigen values
print("Printing the Eigen values of the given square array:\n",
    w)

# printing eigen vectors
print("Printing Right eigenvectors of the given square array:\n",
    v)


Printing the Original square array:
 [[1 2]
 [2 3]]
Printing the Eigen values of the given square array:
 [-0.23606798  4.23606798]
Printing Right eigenvectors of the given square array:
 [[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]


Calculate the Euclidean distance using NumPy

In [6]:
# Python code to find Euclidean distance
# using linalg.norm()

import numpy as np

# initializing points in
# numpy arrays
point1 = np.array((1, 2, 3))
point2 = np.array((1, 1, 1))

# calculating Euclidean distance
# using linalg.norm()
dist = np.linalg.norm(point1 - point2)

# printing Euclidean distance
print(dist)

2.23606797749979


Calculate the QR decomposition of a given matrix using NumPy

In [7]:
import numpy as np


# Original matrix
matrix1 = np.array([[1, 0], [2, 4]])
print(matrix1)

# Decomposition of the said matrix
q, r = np.linalg.qr(matrix1)
print('\nQ:\n', q)
print('\nR:\n', r)


[[1 0]
 [2 4]]

Q:
 [[-0.4472136  -0.89442719]
 [-0.89442719  0.4472136 ]]

R:
 [[-2.23606798 -3.57770876]
 [ 0.          1.78885438]]
